name: test-and-build-image
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VUE_APP_ROLLOUT_KEY: ${{ secrets.VUE_APP_ROLLOUT_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: npm ci
      - run: npm run test:unit

      - name: Record test results to Launchable workspace
        uses: launchableinc/record-build-and-test-results-action@v1.0.0
        with:
          report_path: junit.xml
          test_runner: jest
        if: always()
        env:
          LAUNCHABLE_TOKEN: ${{ secrets.LAUNCHABLE_TOKEN }}

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: junit.xml
          path: junit.xml
